// ---- i18n dictionaries ----
export const i18n = {
  en: {
    navRegister:'Register', navAbout:'About', joinNow:'Join now',
    heroTitle:'Connect volunteers with seniors for warm companionship and daily help',
    heroLead:'BuddyLink supports <strong>senior sign-up</strong> and <strong>volunteer sign-up</strong>. We match by interests and availability. Services include friendly chats, video companionship, reading mail, short walks, groceries/meds pickup, and basic tech help.',
    ctaSenior:'I’m a senior, need help', ctaVolunteer:'I’m a volunteer, want to help',
    registerTitle:'Registration',
    // registerSub:'Choose your role to sign up. Fields are demo only (client-side validation). Hook up your backend at <code>/register/senior</code> and <code>/register/volunteer</code>.',
    tabSenior:'Senior Sign-up', tabVolunteer:'Volunteer Sign-up',
    name:'Name', namePh:'Enter full name', age:'Age', agePh:'e.g., 70', ageHelp:'Optional; helps us prioritize age-appropriate services.',
    phone:'Phone', phonePh:'e.g., 647-123-4567', email:'Email', emailPh:'example@email.com',
    city:'City / Area', cityPh:'e.g., Toronto / Scarborough', contactPref:'Preferred contact', optPhone:'Phone', optEmail:'Email', optVideo:'Video',
    needs:'Needed services (multi-select)', needChat:'Friendly chat', needVideo:'Video companionship', needRead:'Read letters/news', needWalk:'Short walk', needGrocery:'Groceries',needHealth:'Health' ,needTech:'Tech help',
    availability:'Availability', availabilityPh:'e.g., Mon/Wed/Fri 2–5 pm', prefLang:'Preferred language',
    notes:'Notes (health/accessibility)', notesPh:'Wheelchair access, allergies, etc.',
    submitSenior:'Submit senior sign-up', privacyAgree:'By submitting, you agree to our privacy terms.',
    sMsg:'Thanks! (demo) We will contact you soon for matching.',
    skills:'Services you can provide (multi-select)', background:'Background check', bgNo:'Not yet', bgProgress:'In progress', bgYes:'Completed',
    consent:'I agree to the volunteer code of conduct and privacy.', submitVolunteer:'Submit volunteer sign-up', prefill:'Prefill demo', vMsg:'Thanks for signing up! (demo) We’ll match you based on your time and skills.',
    aboutTitle:'About BuddyLink', aboutLead:'This is a demo page in a modern nonprofit style. Integrate it into your project and connect both forms to your backend (Node/Flask/Spring, etc.).',
    about1:'Fully responsive layout', about2:'Accessibility: labels & ARIA', about3:'Basic client validation & messages', about4:'Extensible to auth/database',
    demoNote:'Demo only: submissions show a local success message',
    requiredAlert:'Please complete required fields / consent.',
    descriptionPh:'I focus on companionship and information accessibility for seniors, providing video check-ins, mail/form reading, light errands, and basic digital guidance. I respect privacy and communicate patiently; I’m available on times and can also support online when needed.',
    // Login page
    loginTitle: 'Login',
    loginWelcome: 'Welcome back! Please sign in to continue.',
    labelEmail: 'Email',
    phEmail: 'you@example.com',
    emailHint: 'Use the email you registered with.',
    labelPassword: 'Password',
    phPassword: 'Your password',
    rememberMe: 'Remember me',
    btnLogin: 'Login',
    noAccount: 'Don’t have an account?',
    goRegister: 'Register',
    navHome: 'Home',
    loginMissing: 'Please enter email and password.',
    loginSuccess: 'Login submitted (demo).',
    male: 'Male',
    female: 'Female',
    other: 'Other',
    english: 'English',
    french: 'French',
    language: 'Language',
    navProfile: 'Profile',
    navRegister: 'Register',
    btnrole_senior: 'I’m a senior, need help',
    btnvolunteer_senior: 'I’m a volunteer, want to help',
    signup_senior: 'Senior Sign-up',
    signup_volunteer: 'Volunteer Sign-up',
    backtohome: 'Home',
    introdution: 'BuddyLink supports <strong>senior sign-up</strong> and <strong>volunteer sign-up</strong>. We match by interests and availability. Services include friendly chats, video companionship, reading mail, groceries pickup and health consulation, and basic tech help.',
    introdution_title: 'Connect volunteers with seniors for warm companionship and daily help',
    upcoming_event: 'Upcoming Event',
    description: 'Self-description',
 

    // weekly picker
    Monday: 'Monday',
    Tuesday: 'Tuesday' ,
    Wednesday: 'Wednesday',
    Thursday: 'Thursday',
    Friday: 'Friday',
    Saturday: 'Saturday' ,
    Sunday : 'Sunday',

    day: 'Day',    
    morning: 'Morning',
    afternoon: 'Afternoon',
    evening: 'Evening',

    clear: 'Clear',    

    notes2: 'Additional Requirements',
    notes2Ph: 'Cooking help needed',
    nextweek: 'Schedule for next week',

    askforservice:'Ask for Services',
    askforservice2lines: 'Ask for<br>Services',

    fname: 'First Name',
    lname: 'Last Name',
    password: 'Enter Password',
    repassword: 'Re-enter Password',
    address: 'Address',
    gender:'Gender',

    servetime: 'Serve time',
    pdservice: 'Providing Service',
    rating: 'Rating',

    servicehistory: 'Service History',

    records:'Records',
    totalpage:'total / page ',
    refresh: 'Refresh',
  },
  fr: {
    navRegister:'Inscription', navAbout:'À propos', joinNow:'S’inscrire maintenant',
    heroTitle:'Mettre en relation des bénévoles avec des seniors pour offrir une chaleureuse compagnie et une aide au quotidien.',
    heroLead:'BuddyLink permet <strong>l’inscription des seniors et des bénévoles</strong>. Nous réalisons des mises en relation en fonction des centres d’intérêt et des disponibilités de chacun. Les services proposés incluent des conversations conviviales, de la compagnie en visioconférence, la lecture du courrier, de petites promenades, le retrait de courses ou de médicaments, ainsi qu’une aide informatique de base.',
    ctaSenior:'Je suis un senior, j’ai besoin d’aide', ctaVolunteer:'Je suis bénévole, je veux aider',
    registerTitle:'Inscription',
//    registerSub:'Choisissez votre rôle pour vous inscrire. Les champs sont uniquement des exemples (validation côté client). (validation côté client). Connectez votre backend à l’adresse suivante : <code>/register/senior</code> et <code>/register/volunteer</code>.',
    tabSenior:'Inscription senior', tabVolunteer:'Inscription bénévole',
    name:'Nom', namePh:'Nom complet', age:'Âge', agePh:'ex. 70', ageHelp:'Optionnel ; nous aide à déterminer les services adaptés à l’âge.',
    phone:'Téléphone', phonePh:'ex. 647-123-4567', email:'Courriel', emailPh:'exemple@courriel.com',
    city:'Ville / Quartier', cityPh:'ex. Toronto / Scarborough', contactPref:'Contact préféré', optPhone:'Téléphone', optEmail:'Courriel', optVideo:'Vidéo',
    needs:' Services nécessaires (sélection multiple)', needChat: 'Conversations conviviales', needVideo: 'La compagnie en visioconférence', needRead: 'La lecture du courrier', needWalk:'Petites promenades', needGrocery:' Le retrait de courses ',needHealth:' Le retrait de médicaments ', needTech: 'L’aide informatique de base ',
    availability:'Disponibilités', availabilityPh:'ex. Lun/Me/Ven 14 h–17 h', prefLang:'Langue préférée',
    notes:'Notes (santé/accessibilité)', notesPh:'Accès fauteuil roulant, allergies, etc.',
    submitSenior:'Envoyer l’inscription senior', privacyAgree:'En envoyant, vous acceptez nos conditions de confidentialité.',
    sMsg:'Merci pour votre inscription ! (démo) Nous vous mettrons en relation en fonction de vos disponibilités et de vos compétences.',
    skills:'Services que vous pouvez offrir (multi-sélection)', background: 'Vérification des antécédents judiciaires ', bgNo:'Pas encore', bgProgress:'En cours', bgYes:'Terminée',
    consent:'J’accepte le code de conduite des bénévoles et la politique de confidentialité.', submitVolunteer:'Soumettre votre inscription du bénévole', prefill:'Préremplir (démo)', vMsg:'Merci pour votre inscription ! (démo) Nous vous mettrons en relation en fonction de vos disponibilités et de vos compétences..',
    aboutTitle:'À propos de BuddyLink', aboutLead:'Ceci est une page de démonstration dans un style moderne destiné aux organismes à but non lucratif. Intégrez-la à votre projet et connectez les deux formulaires à votre backend (Node/Flask/Spring, etc.)',
    about1:'Mise en page entièrement responsive', about2:'Accessibilité : libellés et ARIA', about3:'Validation et messages côté client', about4:'Extensible à l’authentification/base de données',
    demoNote: 'Démo uniquement : les envois affichent simplement un message de réussite local.',
    requiredAlert:' Veuillez remplir les champs obligatoires / donner votre consentement.',
    // Login page
    loginTitle: 'Connexion',
    loginWelcome: 'Bon retour ! Veuillez vous connecter pour continuer.',
    labelEmail: 'Email',
    phEmail: 'vous@exemple.com',
    emailHint: ' Utilisez l’adresse email avec laquelle vous vous êtes inscrit(e).',
    labelPassword: 'Mot de passe',
    phPassword: 'Votre mot de passe',
    rememberMe: 'Se souvenir de moi',
    btnLogin: 'Connexion',
    noAccount: 'Vous n’avez pas de compte ?',
    goRegister: 'S’inscrire',
    navHome: 'Accueil',
    loginMissing: 'Veuillez saisir votre e-mail et le mot de passe.',
    loginSuccess: 'Connexion envoyée (démo).',
    male: 'Homme',
    female: 'Femme',
    other: 'Autre',
    english: 'Anglais',
    french: 'Français',
    language: 'Langage',
    navProfile: 'Profil',
    navRegister: 'S’inscrire',
    btnrole_senior: 'Je suis senior, j’ai besoin d’aide',
    btnvolunteer_senior: 'Bénévole, je veux aider',
    signup_senior: 'L’inscription des seniors',
    signup_volunteer: 'L’inscription des bénévoles',
    backtohome: 'L’accueil',
    introdution: 'BuddyLink permet <strong>l’inscription des seniors et des bénévoles</strong>. Nous réalisons des mises en relation en fonction des centres d’intérêt et des disponibilités de chacun. Les services proposés incluent des conversations conviviales, de la compagnie en visioconférence, la lecture du courrier, de petites promenades, le retrait de courses ou de médicaments, ainsi qu’une aide informatique de base',
    introdution_title: ' Mettre en relation des bénévoles avec des seniors pour offrir une chaleureuse compagnie et une aide au quotidien ',
    upcoming_event: 'Événement à venir',
    descriptionPh: 'Je me concentre sur la compagnie et l’accessibilité de l’information pour les personnes âgées. J’offre des visites vidéo, la lecture du courrier et des formulaires, de petites courses légères ainsi qu’un accompagnement numérique de base. Je respecte la vie privée et je communique avec patience ; je suis disponible aux horaires indiqués et je peux également offrir un soutien en ligne si nécessaire.',
    description: 'Présentation personnelle',

    // weekly picker
    Monday: 'Lundi',
    Tuesday: 'Mardi',
    Wednesday: 'Mercredi',
    Thursday: 'Jeudi',
    Friday: 'Vendredi',
    Saturday: 'Samedi',
    Sunday: 'Dimanche',

    day: 'Jour',
    morning: 'Matin',
    afternoon: 'Après-midi',
    evening: 'Soir',

    clear: 'Effacer',

    notes2: 'Demandes supplémentaires',
    notes2Ph: 'Besoin d’aide pour cuisiner',
    nextweek: 'Réserver pour la semaine prochaine',

    askforservice: 'Demander des services',
    askforservice2lines: 'Demander<br>des services',

    fname: 'Prénom',
    lname: 'Nom de famille',
    password: 'Entrez le mot de passe',
    repassword: 'Entrez de nouveau le mot de passe',
    address: 'Adresse',
    gender: 'Genre',

    servetime: 'Heure de service',
    pdservice: 'Prestation de service',
    rating: 'Évaluation',

    servicehistory: 'Historique des services',
    records:'Enregistrements',
    totalpage:'au total / page ',
    refresh: "Rafraîchir",

  }
};


